- hosts: name_larissa-devs*
  gather_facts: no
  tasks:
  - name: Get instance id
    uri:
      url: http://169.254.169.254/latest/meta-data/instance-id
      return_content: yes
    register: instance_id
  - name: Set hostname
    hostname:
      name: "{{ instance_id.content }}"
    become: yes
